language: php

php:
  - 7.0

services:
  - postgresql

before_script:
  - psql -c 'create database opif_testing;' -U postgres
  - cp .env.travis .env
  - composer install
  - php artisan migrate --env=testing
  - php artisan key:generate

script:
  - vendor/bin/phpunit

addons:
  postgresql: "9.5"