language: php

php:
  - 7.1

services:
  - postgresql

before_script:
  - psql -c 'create database opif_testing;' -U postgres
  - cp .env.travis .env
  - composer install

script:
  - vendor/bin/phpunit