<?php
namespace Tests\Unit;

use App\Core\Telegram\CallbackCommandBus;
use App\Telegram\CallbackCommands\CallbackCommand;
use Telegram\Bot\Api;
use Telegram\Bot\Objects\Update;
use Tests\TestCase;

class CallbackCommandBusTest extends TestCase
{
    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        \Mockery::close();
    }

    /** @test */
    public function a_bus_should_call_the_command()
    {
        $telegramMock = \Mockery::mock(Api::class);
        $updateMock = \Mockery::mock(Update::class);

        $commandMock = \Mockery::mock(CallbackCommand::class, [$telegramMock])->makePartial();
        $commandMock->shouldReceive("getName")->andReturn("testcommand");
        $commandMock->shouldReceive("setParameters")->andReturnSelf();
        $commandMock->shouldReceive("handle");

        $bus = new CallbackCommandBus($telegramMock);
        $bus->addCommand($commandMock);
        $bus->handle("testcommand:test", $updateMock);
    }
}