<?php
namespace Tests\Unit;

use App\Core\Parsers\HtmlCourseParser;
use App\Opif;
use Tests\TestCase;
use VCR\VCR;

class ParserTest extends TestCase
{
    function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        VCR::configure()->setCassettePath(base_path("tests/fixtures"));
    }

    /** @test */
    function a_parser_should_parse_courses()
    {
        VCR::turnOn();
        VCR::insertCassette('alfacapital.yml');

        /** @var HtmlCourseParser $parser */
        $parser = $this->app->make(HtmlCourseParser::class);
        $opif = Opif::find(1);

        $result = $parser->parse($opif);

        VCR::eject();
        VCR::turnOff();

        $this->assertArrayHasKey('prev', $result);
        $this->assertArrayHasKey('curr', $result);
        $this->assertArrayHasKey('date', $result['prev']);
        $this->assertArrayHasKey('course', $result['prev']);
        $this->assertArrayHasKey('date', $result['curr']);
        $this->assertArrayHasKey('course', $result['curr']);
    }
}